sudo: required
services:
    - docker
before_install:
    - docker build -t hiroshimashu/docker-react -f Dockerfile.dev .

script: 
    - docker run hiroshimashu/docker-react npm run test -- --coverage